config/routes.rb
Rails.application.routes.draw do
  
  root "tracks#index"

  get "pages/about"
  
  resources :tracks

  resources :users, only: %i[new create]
  resource :session, only: %i[new create destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/track.rb
class Track < ApplicationRecord

    belongs_to :user

    has_one_attached :audio, dependent: :destroy

    has_one_attached :image, dependent: :destroy

    validates :audio, blob: { content_type: :audio }

    validates :image, blob: { content_type: :image }

    validates_presence_of :song, on: :create, message: "can't be blank"

    validates_presence_of :artist, on: :create, message: "can't be blank"

    validates_presence_of :audio, on: :create, message: "can't be blank"

    validates_presence_of :image, on: :create, message: "can't be blank"

    validates :song, length: { maximum: 40 }

    validates :artist, length: { maximum: 20 }

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :tracks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to tracks_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to tracks_url, notice: 'Logged out!'
  end
  
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: %i[ show edit update destroy ]

  # GET /tracks or /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1 or /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks or /tracks.json
  def create
    @track = Track.new(track_params)
    @track.user = current_user
    respond_to do |format|
      if @track.save
        format.html { redirect_to track_url(@track), notice: "Track was successfully created." }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1 or /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to track_url(@track), notice: "Track was successfully updated." }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1 or /tracks/1.json
  def destroy
    if @track.user == current_user
      @track.destroy
      respond_to do |format|
        format.html { redirect_to tracks_url, notice: "Track was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to tracks_url, notice: "This is not your track" }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def track_params
      params.require(:track).permit(:song, :artist, :audio, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to tracks_url, notice: 'Thank you for signing up!'
      else
        render :new
      end
    end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/tracks">
        <img src="https://seeklogo.com/images/M/music-box-logo-52D9A99D76-seeklogo.com.png" width="112" height="28">
      </a>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item">
          <%= link_to "New track", new_track_path, class: "navbar-item"%>
        </a>

        <a class="navbar-item">
          <%= link_to "About", "/pages/about", class: "navbar-item"%>
        </a>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <% if logged_in? %>
            <%= "Hello #{current_user.name}!" %> 
            <%= link_to 'Logout', session_path, class: "button is-danger", data: {turbo_method: :delete} %>
          <% else %>
            <div class="buttons">
            <%= link_to 'Sign Up', new_user_path, class: "button is-primary" %>
            <%= link_to 'Log In', new_session_path, class: "button is-light" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="background-color: #E8E8E8">
  <head>
    <title>MusicBox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">

    <%= render 'layouts/header' %>
  </head>

  <body >

    <style>
      .flex-container {
      display: flex;
      }

      .flex-container > div {
        margin: 10px;
      }

      .column-container {
        display: flex;
        flex-direction: column;
      }
    </style>

    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>My Pet-Project</p>

app/views/tracks/_form.html.erb
<%= form_with(model: track) do |form| %>
  <% if track.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
        <% track.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :song, style: "display: block" %>
    <%= form.text_field :song %>
  </div>

  <div>
    <%= form.label :artist, style: "display: block" %>
    <%= form.text_field :artist %>
  </div>

  <div>
    <%= form.label :audio, style: "display: block" %>
    <%= form.file_field :audio %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tracks/_track.html.erb
<div id="<%= dom_id track %>">

  <div class="flex-container">
  
    <div>
      <%= image_tag(track.image, class: "message-image", height: 100, width: 100) %>
    </div>

    <div class="column-container">
      <div>
        <strong><%= track.song %></strong>
      </div>
      <div>
        <%= track.artist %>
      </div>
    
      <div>
        <%= audio_tag(url_for(track.audio), class: "message-audio", controls: "") %>
      </div>
    </div>
  </div>
</div>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render "form", track: @track %>

<br>

<div>
  <%= link_to "Show this track", @track %> |
  <%= link_to "Back to tracks", tracks_path %>
</div>

app/views/tracks/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="tracks" style="padding:50px">
  <% @tracks.each do |track| %>
    <%= render track %>
    <p>
      <%= link_to "Show this track", track, class: "button is-dark  button is-small"%>
    </p>
    <br>
    <div style="height: 2px; background-color: #CECECE"></div>
  <% end %>
</div>
 

app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render "form", track: @track %>

<br>

<div>
  <%= link_to "Back to tracks", tracks_path, class: "button is-dark" %>
</div>

app/views/tracks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @track %>

<p>
    <i class="fa-solid fa-user"></i>
    <%= @track.user.name %>
</p>
<br>
<div>
  <%= link_to "Edit this track", edit_track_path(@track), class: "button is-warning" %> 
  <%= link_to "Back to tracks", tracks_path, class: "button is-dark" %>

</div>
<br>
  <%= button_to "Destroy this track", @track, class: "button is-danger", method: :delete %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, 'error') %> prohibited this user from signing up:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="actions">
    <%= f.submit 'Sign Up' %>
  </div>
<% end %>